/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package task.tree;

import javax.swing.JFrame;
import javax.swing.JLabel;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
//    	Scanner scanner = new Scanner(System.in);
        System.out.println(new App().getGreeting());
        
        RootTask rt = new RootTask();
        ChildTask ct1 = new ChildTask("one", rt, 1);
        ChildTask ct2 = new ChildTask("two", rt, 1);
        ChildTask ct3 = new ChildTask("three", rt, 1);
        ChildTask[] ar1 = {ct1, ct2};
        ChildTask[] ar2 = {ct1, ct2, ct3};
        
        rt.setChildren(ar1);
        rt.setChildren(ar2);
        
        
        
        
        JFrame frame = new JFrame();
        JLabel label = new JLabel("<html> bo <br/> bo </html>");
        frame.setTitle("Task tree (pre alpha)");
        frame.setSize(420,420);
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.add(label);
        
        
        CLIBot cli = new CLIBot();
        cli.start();
        
    }
}
