/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package task.tree;
//import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
//    	Scanner scanner = new Scanner(System.in);
        System.out.println(new App().getGreeting());
        Task rootTask = new Task("root");
        Task branchTask = new Task("branch task", rootTask, 1);
        System.out.println(branchTask.summary());
        
        CLIBot cli = new CLIBot();
        cli.start();
        
    }
}
